import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeContext";
import ThemeToggle from "@/components/ThemeToggle";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>UmaMusume Statistics</title>
        <meta name="apple-mobile-web-app-title" content="MyWebSite" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <ThemeProvider>
              <header>
                {/* <ThemeToggle /> */}
              </header>
        {children}
            </ThemeProvider>
        <footer className="p-4 text-center text-sm text-gray-500">
          <p>&copy; {new Date().getFullYear()} MrCocoNuat</p>
          <p>This site is not affiliated with Cygames or any of its partners.</p>
          <p>Uma Musume and all related trademarks are the property of Cygames.</p>
          <p>
            GPLv3 Source code available on{" "}
            <a
              href="https://github.com/MrCocoNuat/uma-stats"
              className="text-blue-500 hover:underline"
            >
              GitHub
            </a>
          </p>
        </footer>
      </body>
    </html>
  );
}
